Added homework_18_310123
kate-lvlup/homework pull request #16
Opened 2023-02-03 13:48 UTC by kate-lvlup

Hi Dima,
Could you check my homework18(HashMap, TreeMap)?

Thanks in advance!

2023-02-07 13:57 UTC, YeaaaaH commented on homework_18_310123/src/TreeMapMethods.java
> +    //    Java Collection: TreeMap Exercises [26 exercises with solution]
??

2023-02-07 14:00 UTC, YeaaaaH commented on homework_18_310123/src/HashMapMethods.java
> +    //    Java Collection: HashMap Exercises [12 exercises with solution]
??

2023-02-07 14:00 UTC, YeaaaaH requested changes
remove it)

2023-02-09 09:50 UTC, kate-lvlup commented on homework_18_310123/src/TreeMapMethods.java
> +    //    Java Collection: TreeMap Exercises [26 exercises with solution]
Fixed.

2023-02-09 09:51 UTC, kate-lvlup commented on homework_18_310123/src/HashMapMethods.java
> +    //    Java Collection: HashMap Exercises [12 exercises with solution]
Fixed

2023-02-09 09:53 UTC, YeaaaaH approved these changes

2023-02-09 09:55 UTC, merged