Added (Edit/Update User (JDBC, SQL)) into homework_10_proj_101222
kate-lvlup/homework pull request #34
Opened 2023-04-22 06:14 UTC by kate-lvlup

2023-04-22 11:14 UTC, YeaaaaH commented on homework_10_proj_101222/src/main/java/app/RegistrationApp.java
> +                        userService.saveUserAfterEditing(userAfterEdit);
rename

2023-04-22 11:15 UTC, YeaaaaH requested changes
fixs after lesson

2023-04-27 13:27 UTC, kate-lvlup commented on homework_10_proj_101222/src/main/java/app/RegistrationApp.java
> +                        userService.saveUserAfterEditing(userAfterEdit);
saveUserAfterEditing() was deleted. New logic was applied.

2023-04-27 13:29 UTC, kate-lvlup commented
fixs after lesson was added

2023-04-27 20:07 UTC, YeaaaaH approved these changes

2023-04-30 08:08 UTC, merged